//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodBankDatabaseEntities : DbContext
    {
        public BloodBankDatabaseEntities()
            : base("name=BloodBankDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood_Group> Blood_Group { get; set; }
        public virtual DbSet<Blood_Stock> Blood_Stock { get; set; }
        public virtual DbSet<Donated_Blood> Donated_Blood { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Eye_Color> Eye_Color { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Receiver> Receivers { get; set; }
    }
}
