//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donated_Blood
    {
        public int id { get; set; }
        public int Donor_ID { get; set; }
        public int Receiver_ID { get; set; }
    
        public virtual Receiver Receiver { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
